name: "Build and publish images"

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-publish-ubuntu:
    name: "Build and publish ubuntu version-specific images"
    uses: ./.github/workflows/build-and-publish-ubuntu.yaml
    secrets: inherit
  build-and-publish-latest:
    name: "Build and publish latest images"
    uses: ./.github/workflows/build-and-publish-latest.yaml
    secrets: inherit
