name: "Build and publish latest images"

on:
  workflow_call:
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1

jobs:
  build-and-publish-latest:
    name: "Build and publish latest and ubuntu"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Log in to Docker"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "Build images"
        run: |
          version_label=$GITHUB_REF_NAME-$(date '+%Y%m%d')
          docker build --file "$GITHUB_WORKSPACE/Dockerfile.ubuntu" --target steamcmd --tag nhalase/steamcmd:ubuntu --tag nhalase/steamcmd:latest --label "version=$version_label" --label "github.ref=$GITHUB_REF" --label "github.runid=$GITHUB_RUN_ID" "$GITHUB_WORKSPACE"
      - name: "Test images"
        run: |
          docker run --rm nhalase/steamcmd:latest
      - name: "Publish images"
        run: |
          docker push nhalase/steamcmd:latest
          docker push nhalase/steamcmd:ubuntu
